// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tgjpjhqzwkwdrowgppdr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRnanBqaHF6d2t3ZHJvd2dwcGRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA5ODg1MTQsImV4cCI6MjA4NjU2NDUxNH0.PQWvAWv3oKAosYrZ4Z50rb6fjXjwGTHtGUXdHbYd1r4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});